currLabel: 'Plugin Store'
customIcon: null
enabled: false
handle: plugin-store
icon: plug
layout: bb1b5a06-bbfb-4097-a6bf-5bdd232de146 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Plugin Store'
prevLevel: 1
prevParent: null
prevUrl: plugin-store
sortOrder: 10
type: craft
url: plugin-store
