currLabel: Entries
customIcon: null
enabled: false
handle: entries
icon: newspaper
layout: bb1b5a06-bbfb-4097-a6bf-5bdd232de146 # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 3
type: craft
url: entries
