app = "gll-checkout-postgres"
primary_region = "fra"

[build]

[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 5432

  [[services.tcp_checks]]
    interval = 10000
    timeout  = 2000

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mount]
  source      = "postgres"
  destination = "/var/lib/postgresql/"


#app = "gll-checkout-postgres"
#primary_region = 'fra'
#
#[build]
#
#[http_service]
#port = 5432
##force_https = false
#auto_stop_machines = 'stop'
#auto_start_machines = true
#min_machines_running = 0
#processes = ['app']
#
#[[vm]]
#memory = '256mb'
#cpus = 1
#memory_mb = 256
#
#[mount]
#source      = "postgres"
#destination = "/var/lib/postgresql/"

#[experimental]
#  private_network = true

#[build]
#  image = "postgres:16"


#[[services]]
#  internal_port = 5432
#  protocol      = "tcp"

#[[services.tcp_checks]]
#  interval = 10000
#  timeout  = 2000
